name: Bugs and Errors
description: File a bug report, or tell us about another error
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to open this issue.!

        Before submitting, please ensure you're using go 1.16.x. Please see [the FAQ](/FAQ.md) for more information.
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: ""
    validations:
      required: true
  - type: textarea
    id: version
    attributes:
      label: Go Version
      description: What is the output of `go version`?
      placeholder: go version go1.....
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
