#include "textflag.h"

#define m_fpstate 32

TEXT alltraps(SB), NOSPLIT, $0
	PUSHQ R15
	PUSHQ R14
	PUSHQ R13
	PUSHQ R12
	PUSHQ R11
	PUSHQ R10
	PUSHQ R9
	PUSHQ R8
	PUSHQ DI
	PUSHQ SI
	PUSHQ BP
	PUSHQ DX
	PUSHQ CX
	PUSHQ BX
	PUSHQ AX

	// CX store mythread
	MOVQ   0(GS), CX
	MOVQ   m_fpstate(CX), DX
	FXSAVE (DX)

	// make top stack frame
	XORQ  BP, BP
	PUSHQ SP
	CALL  ·dotrap(SB)
	ADDQ  $8, SP
	JMP   ·trapret(SB)

TEXT ·trapret(SB), NOSPLIT, $0
	// CX store mythread
	MOVQ 0(GS), CX

	// restore FPU
	MOVQ    m_fpstate(CX), DX
	FXRSTOR (DX)

	POPQ AX
	POPQ BX
	POPQ CX
	POPQ DX
	POPQ BP
	POPQ SI
	POPQ DI
	POPQ R8
	POPQ R9
	POPQ R10
	POPQ R11
	POPQ R12
	POPQ R13
	POPQ R14
	POPQ R15

	ADDQ $16, SP // skip trapno and errcode

	ADDQ $8, SP // NOTE: skip return address of <autogenerated> function (added in Go 1.17).

	// Dump of assembler code for function github.com/icexin/eggos/kernel.trapret<autogenerated>:
	// => 0x00000000002bbf60 <+0>:   call   0x2b9e40 <github.com/icexin/eggos/kernel.trapret>
	//    0x00000000002bbf65 <+5>:   xorps  %xmm15,%xmm15
	//    0x00000000002bbf69 <+9>:   mov    %fs:0xfffffffffffffff8,%r14
	//    0x00000000002bbf72 <+18>:  ret

	IRETQ

