on: [pull_request]
name: CI
jobs:
  ubuntu-latest:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.13.x

    - name: Install Mage
      run: |
        go get github.com/magefile/mage

    - name: Install Grub
      run: |
        apt install grub-common grub-pc-bin

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build
      run: |
        diff -u <(echo -n) <(gofmt -d $(find . -type f -name '*.go')) 
        mage -v iso

  macos-latest:
    runs-on: macos-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.13.x

    - name: Install Mage
      run: |
        go get github.com/magefile/mage

    - name: Install Elf Gcc
      run: |
        brew install x86_64-elf-gcc

    - name: Install Grub
      run: |
        brew install hawkw/homebrew-grub/grub

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build
      run: |
        diff -u <(echo -n) <(gofmt -d $(find . -type f -name '*.go')) 
        mage -v iso