on: 
  push:
    branches:
      - main
  pull_request:

name: CI
jobs:
  ubuntu-latest:
    runs-on: ubuntu-21.04
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.x

    - name: Install Mage
      run: |
        go get github.com/magefile/mage

    - name: Install Qemu
      run: |
        sudo apt-get update && sudo apt-get install -y qemu-system-x86

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build
      run: |
        diff -u <(echo -n) <(gofmt -d $(find . -type f -name '*.go')) 
        mage -v multiboot
        mage -v iso
        mage -v test

  macos-latest:
    runs-on: macos-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.x

    - name: Install Mage
      run: |
        go get github.com/magefile/mage

    - name: Install Elf Gcc
      run: |
        brew install x86_64-elf-gcc

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build
      run: |
        diff -u <(echo -n) <(gofmt -d $(find . -type f -name '*.go')) 
        mage -v multiboot
        mage -v kernel