// Code generated by genvector.go using 'go generate'. DO NOT EDIT.
package kernel

//go:nosplit
func trap0()

//go:nosplit
func trap1()

//go:nosplit
func trap2()

//go:nosplit
func trap3()

//go:nosplit
func trap4()

//go:nosplit
func trap5()

//go:nosplit
func trap6()

//go:nosplit
func trap7()

//go:nosplit
func trap8()

//go:nosplit
func trap9()

//go:nosplit
func trap10()

//go:nosplit
func trap11()

//go:nosplit
func trap12()

//go:nosplit
func trap13()

//go:nosplit
func trap14()

//go:nosplit
func trap15()

//go:nosplit
func trap16()

//go:nosplit
func trap17()

//go:nosplit
func trap18()

//go:nosplit
func trap19()

//go:nosplit
func trap20()

//go:nosplit
func trap21()

//go:nosplit
func trap22()

//go:nosplit
func trap23()

//go:nosplit
func trap24()

//go:nosplit
func trap25()

//go:nosplit
func trap26()

//go:nosplit
func trap27()

//go:nosplit
func trap28()

//go:nosplit
func trap29()

//go:nosplit
func trap30()

//go:nosplit
func trap31()

//go:nosplit
func trap32()

//go:nosplit
func trap33()

//go:nosplit
func trap34()

//go:nosplit
func trap35()

//go:nosplit
func trap36()

//go:nosplit
func trap37()

//go:nosplit
func trap38()

//go:nosplit
func trap39()

//go:nosplit
func trap40()

//go:nosplit
func trap41()

//go:nosplit
func trap42()

//go:nosplit
func trap43()

//go:nosplit
func trap44()

//go:nosplit
func trap45()

//go:nosplit
func trap46()

//go:nosplit
func trap47()

//go:nosplit
func trap48()

//go:nosplit
func trap49()

//go:nosplit
func trap50()

//go:nosplit
func trap51()

//go:nosplit
func trap52()

//go:nosplit
func trap53()

//go:nosplit
func trap54()

//go:nosplit
func trap55()

//go:nosplit
func trap56()

//go:nosplit
func trap57()

//go:nosplit
func trap58()

//go:nosplit
func trap59()

//go:nosplit
func trap60()

//go:nosplit
func trap61()

//go:nosplit
func trap62()

//go:nosplit
func trap63()

//go:nosplit
func trap64()

//go:nosplit
func trap65()

//go:nosplit
func trap66()

//go:nosplit
func trap67()

//go:nosplit
func trap68()

//go:nosplit
func trap69()

//go:nosplit
func trap70()

//go:nosplit
func trap71()

//go:nosplit
func trap72()

//go:nosplit
func trap73()

//go:nosplit
func trap74()

//go:nosplit
func trap75()

//go:nosplit
func trap76()

//go:nosplit
func trap77()

//go:nosplit
func trap78()

//go:nosplit
func trap79()

//go:nosplit
func trap80()

//go:nosplit
func trap81()

//go:nosplit
func trap82()

//go:nosplit
func trap83()

//go:nosplit
func trap84()

//go:nosplit
func trap85()

//go:nosplit
func trap86()

//go:nosplit
func trap87()

//go:nosplit
func trap88()

//go:nosplit
func trap89()

//go:nosplit
func trap90()

//go:nosplit
func trap91()

//go:nosplit
func trap92()

//go:nosplit
func trap93()

//go:nosplit
func trap94()

//go:nosplit
func trap95()

//go:nosplit
func trap96()

//go:nosplit
func trap97()

//go:nosplit
func trap98()

//go:nosplit
func trap99()

//go:nosplit
func trap100()

//go:nosplit
func trap101()

//go:nosplit
func trap102()

//go:nosplit
func trap103()

//go:nosplit
func trap104()

//go:nosplit
func trap105()

//go:nosplit
func trap106()

//go:nosplit
func trap107()

//go:nosplit
func trap108()

//go:nosplit
func trap109()

//go:nosplit
func trap110()

//go:nosplit
func trap111()

//go:nosplit
func trap112()

//go:nosplit
func trap113()

//go:nosplit
func trap114()

//go:nosplit
func trap115()

//go:nosplit
func trap116()

//go:nosplit
func trap117()

//go:nosplit
func trap118()

//go:nosplit
func trap119()

//go:nosplit
func trap120()

//go:nosplit
func trap121()

//go:nosplit
func trap122()

//go:nosplit
func trap123()

//go:nosplit
func trap124()

//go:nosplit
func trap125()

//go:nosplit
func trap126()

//go:nosplit
func trap127()

//go:nosplit
func trap128()

//go:nosplit
func trap129()

//go:nosplit
func trap130()

//go:nosplit
func trap131()

//go:nosplit
func trap132()

//go:nosplit
func trap133()

//go:nosplit
func trap134()

//go:nosplit
func trap135()

//go:nosplit
func trap136()

//go:nosplit
func trap137()

//go:nosplit
func trap138()

//go:nosplit
func trap139()

//go:nosplit
func trap140()

//go:nosplit
func trap141()

//go:nosplit
func trap142()

//go:nosplit
func trap143()

//go:nosplit
func trap144()

//go:nosplit
func trap145()

//go:nosplit
func trap146()

//go:nosplit
func trap147()

//go:nosplit
func trap148()

//go:nosplit
func trap149()

//go:nosplit
func trap150()

//go:nosplit
func trap151()

//go:nosplit
func trap152()

//go:nosplit
func trap153()

//go:nosplit
func trap154()

//go:nosplit
func trap155()

//go:nosplit
func trap156()

//go:nosplit
func trap157()

//go:nosplit
func trap158()

//go:nosplit
func trap159()

//go:nosplit
func trap160()

//go:nosplit
func trap161()

//go:nosplit
func trap162()

//go:nosplit
func trap163()

//go:nosplit
func trap164()

//go:nosplit
func trap165()

//go:nosplit
func trap166()

//go:nosplit
func trap167()

//go:nosplit
func trap168()

//go:nosplit
func trap169()

//go:nosplit
func trap170()

//go:nosplit
func trap171()

//go:nosplit
func trap172()

//go:nosplit
func trap173()

//go:nosplit
func trap174()

//go:nosplit
func trap175()

//go:nosplit
func trap176()

//go:nosplit
func trap177()

//go:nosplit
func trap178()

//go:nosplit
func trap179()

//go:nosplit
func trap180()

//go:nosplit
func trap181()

//go:nosplit
func trap182()

//go:nosplit
func trap183()

//go:nosplit
func trap184()

//go:nosplit
func trap185()

//go:nosplit
func trap186()

//go:nosplit
func trap187()

//go:nosplit
func trap188()

//go:nosplit
func trap189()

//go:nosplit
func trap190()

//go:nosplit
func trap191()

//go:nosplit
func trap192()

//go:nosplit
func trap193()

//go:nosplit
func trap194()

//go:nosplit
func trap195()

//go:nosplit
func trap196()

//go:nosplit
func trap197()

//go:nosplit
func trap198()

//go:nosplit
func trap199()

//go:nosplit
func trap200()

//go:nosplit
func trap201()

//go:nosplit
func trap202()

//go:nosplit
func trap203()

//go:nosplit
func trap204()

//go:nosplit
func trap205()

//go:nosplit
func trap206()

//go:nosplit
func trap207()

//go:nosplit
func trap208()

//go:nosplit
func trap209()

//go:nosplit
func trap210()

//go:nosplit
func trap211()

//go:nosplit
func trap212()

//go:nosplit
func trap213()

//go:nosplit
func trap214()

//go:nosplit
func trap215()

//go:nosplit
func trap216()

//go:nosplit
func trap217()

//go:nosplit
func trap218()

//go:nosplit
func trap219()

//go:nosplit
func trap220()

//go:nosplit
func trap221()

//go:nosplit
func trap222()

//go:nosplit
func trap223()

//go:nosplit
func trap224()

//go:nosplit
func trap225()

//go:nosplit
func trap226()

//go:nosplit
func trap227()

//go:nosplit
func trap228()

//go:nosplit
func trap229()

//go:nosplit
func trap230()

//go:nosplit
func trap231()

//go:nosplit
func trap232()

//go:nosplit
func trap233()

//go:nosplit
func trap234()

//go:nosplit
func trap235()

//go:nosplit
func trap236()

//go:nosplit
func trap237()

//go:nosplit
func trap238()

//go:nosplit
func trap239()

//go:nosplit
func trap240()

//go:nosplit
func trap241()

//go:nosplit
func trap242()

//go:nosplit
func trap243()

//go:nosplit
func trap244()

//go:nosplit
func trap245()

//go:nosplit
func trap246()

//go:nosplit
func trap247()

//go:nosplit
func trap248()

//go:nosplit
func trap249()

//go:nosplit
func trap250()

//go:nosplit
func trap251()

//go:nosplit
func trap252()

//go:nosplit
func trap253()

//go:nosplit
func trap254()

//go:nosplit
func trap255()

var vectors = [...]func(){
	trap0,
	trap1,
	trap2,
	trap3,
	trap4,
	trap5,
	trap6,
	trap7,
	trap8,
	trap9,
	trap10,
	trap11,
	trap12,
	trap13,
	trap14,
	trap15,
	trap16,
	trap17,
	trap18,
	trap19,
	trap20,
	trap21,
	trap22,
	trap23,
	trap24,
	trap25,
	trap26,
	trap27,
	trap28,
	trap29,
	trap30,
	trap31,
	trap32,
	trap33,
	trap34,
	trap35,
	trap36,
	trap37,
	trap38,
	trap39,
	trap40,
	trap41,
	trap42,
	trap43,
	trap44,
	trap45,
	trap46,
	trap47,
	trap48,
	trap49,
	trap50,
	trap51,
	trap52,
	trap53,
	trap54,
	trap55,
	trap56,
	trap57,
	trap58,
	trap59,
	trap60,
	trap61,
	trap62,
	trap63,
	trap64,
	trap65,
	trap66,
	trap67,
	trap68,
	trap69,
	trap70,
	trap71,
	trap72,
	trap73,
	trap74,
	trap75,
	trap76,
	trap77,
	trap78,
	trap79,
	trap80,
	trap81,
	trap82,
	trap83,
	trap84,
	trap85,
	trap86,
	trap87,
	trap88,
	trap89,
	trap90,
	trap91,
	trap92,
	trap93,
	trap94,
	trap95,
	trap96,
	trap97,
	trap98,
	trap99,
	trap100,
	trap101,
	trap102,
	trap103,
	trap104,
	trap105,
	trap106,
	trap107,
	trap108,
	trap109,
	trap110,
	trap111,
	trap112,
	trap113,
	trap114,
	trap115,
	trap116,
	trap117,
	trap118,
	trap119,
	trap120,
	trap121,
	trap122,
	trap123,
	trap124,
	trap125,
	trap126,
	trap127,
	trap128,
	trap129,
	trap130,
	trap131,
	trap132,
	trap133,
	trap134,
	trap135,
	trap136,
	trap137,
	trap138,
	trap139,
	trap140,
	trap141,
	trap142,
	trap143,
	trap144,
	trap145,
	trap146,
	trap147,
	trap148,
	trap149,
	trap150,
	trap151,
	trap152,
	trap153,
	trap154,
	trap155,
	trap156,
	trap157,
	trap158,
	trap159,
	trap160,
	trap161,
	trap162,
	trap163,
	trap164,
	trap165,
	trap166,
	trap167,
	trap168,
	trap169,
	trap170,
	trap171,
	trap172,
	trap173,
	trap174,
	trap175,
	trap176,
	trap177,
	trap178,
	trap179,
	trap180,
	trap181,
	trap182,
	trap183,
	trap184,
	trap185,
	trap186,
	trap187,
	trap188,
	trap189,
	trap190,
	trap191,
	trap192,
	trap193,
	trap194,
	trap195,
	trap196,
	trap197,
	trap198,
	trap199,
	trap200,
	trap201,
	trap202,
	trap203,
	trap204,
	trap205,
	trap206,
	trap207,
	trap208,
	trap209,
	trap210,
	trap211,
	trap212,
	trap213,
	trap214,
	trap215,
	trap216,
	trap217,
	trap218,
	trap219,
	trap220,
	trap221,
	trap222,
	trap223,
	trap224,
	trap225,
	trap226,
	trap227,
	trap228,
	trap229,
	trap230,
	trap231,
	trap232,
	trap233,
	trap234,
	trap235,
	trap236,
	trap237,
	trap238,
	trap239,
	trap240,
	trap241,
	trap242,
	trap243,
	trap244,
	trap245,
	trap246,
	trap247,
	trap248,
	trap249,
	trap250,
	trap251,
	trap252,
	trap253,
	trap254,
	trap255,
}
